spring.application.name=ecommerce

server.port=5454


spring.datasource.url=jdbc:mysql://localhost:3306/e-commerce-data?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=arjun12@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=arjun123456789012345678901234567890123@#
jwt.expiration=86400000


cloudinary.url=cloudinary://894396117118274:ucvAatPfvvbj0il0o9D3I78ugHU@mr8gsepp

#cloudinary.cloud-name=${mr8gsepp}
#cloudinary.api-key=${894396117118274}
#cloudinary.api-secret=${ucvAatPfvvbj0il0o9D3I78ugHU}
